services:
  # Backend API
  - type: web
    name: youtube-studio-backend
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://mdoocfrbqttyjrmeojbf.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_ORIGINS
        value: "*"

  # Frontend
  - type: web
    name: youtube-studio-frontend
    runtime: static
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://youtube-studio-backend.onrender.com
      - key: VITE_SUPABASE_URL
        value: https://mdoocfrbqttyjrmeojbf.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kb29jZnJicXR0eWpybWVvamJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3Mjc5OTAsImV4cCI6MjA3NjMwMzk5MH0.0oAGMvKutDpyt7hw0FS7XO4-9g-xmMuZpNL7eCZZ5wY
